# Generated by Django 4.0.1 on 2023-08-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_college_department_yearstudent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='branch',
            new_name='subcollege',
        ),
        migrations.RenameField(
            model_name='subcollege',
            old_name='Subcollege',
            new_name='college',
        ),
    ]
