# Generated by Django 4.0.1 on 2023-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_branch_course_subcollege_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='name',
            field=models.CharField(default='koo', max_length=244),
        ),
    ]
