# Generated by Django 4.0.1 on 2023-08-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_achievements_image_buses_image_canteen_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentplacement',
            name='company_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='job_role',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='package',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='pakageLpa',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='studentname',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='app.yearstudent'),
        ),
    ]
