# Generated by Django 4.0.1 on 2023-09-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_college_aboutprincipal_college_hprincipaldimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearstudent',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placedstudentclg', to='app.college'),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='college',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
