# Generated by Django 4.0.1 on 2023-09-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_yearstudent_college_alter_studentplacement_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
