# Generated by Django 4.0.1 on 2023-09-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_event_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Events_images/')),
                ('Events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.event')),
            ],
        ),
    ]
