# Generated by Django 4.0.1 on 2023-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_image_remove_eventimages_image_eventimages_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimages',
            name='images',
        ),
        migrations.AddField(
            model_name='eventimages',
            name='image',
            field=models.ImageField(null=True, upload_to='Events_images2/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
